// <auto-generated />
namespace doan_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _remove_one_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_remove_one_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202007050629163__remove_one_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
