// <auto-generated />
namespace doan_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _add_new_notmapped_img : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_add_new_notmapped_img));
        
        string IMigrationMetadata.Id
        {
            get { return "202007050657123__add_new_notmapped_img"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
