// <auto-generated />
namespace doan_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_vitual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_vitual));
        
        string IMigrationMetadata.Id
        {
            get { return "202007060749295_add_vitual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
